name: Build LaTeX document
on: 
  push:
    paths:
    - '*'
    - '!*.pdf'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: shodd_jacob_resume.tex

      - name: upload artifact
        uses: actions/upload-artifact@master
        with:
          name: shodd_jacob_resume.pdf
          path: ./shodd_jacob_resume.pdf
