name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: shodd_jacob_resume.tex
      - name: uploading pdf
        uses: actions/upload-artifact@master
        with:
          name: shodd_jacob_resume.pdf
          path: ./
